# Extend the specified Python image
FROM mcr.microsoft.com/vscode/devcontainers/python:3.12-bullseye

COPY .bash_aliases /home/vscode/.bash_aliases

# Specify the default command, if any, or override with your own command
CMD ["bash"]
